### ISSUE TITLE
用户管理头像上传BUG

### ISSUE THREAD

**Issue by waynedream** [rstyro/admin-plus#3]
![Snipaste_2019-08-02_10-11-47](https://user-images.githubusercontent.com/38806363/62339266-fb7d3580-b50d-11e9-867b-98c9deb0259b.png)
图中此句应该注释掉，不然js中图片上传无法完成

ps: 找了好久，终于找到问题所在，另外感谢开源，从这项目中学到了很多

**Comment by rstyro** [comment]
谢谢，应该是上次测试的时候忘记注释了，已更新

**Comment by waynedream** [comment]
您好，我在部署admin-plus时，用java -jar运行，弹出banner后，看不到后面输出的内容，全黑，ctrl+c或者ctrl+v都无法退出。这是怎么回事？


环境:阿里云服务器 centOS7，mysql5.7





---原始邮件---
发件人: "帅大叔"<notifications@github.com>
发送时间: 2019年8月3日(星期六) 中午11:14
收件人: "rstyro/admin-plus"<admin-plus@noreply.github.com>;
抄送: "waynedream"<1203294117@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [rstyro/admin-plus] 用户管理头像上传BUG (#3)



谢谢，应该是上次测试的时候忘记注释了，已更新

**Comment by rstyro** [comment]
nohup java-jar admin-plus.jar &
不行的话， 看看日志。
